version: '3.8'

services:
  cpp-server:
    build:
      context: . # Builds from the root using existing C++ Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # volumes: # uncommment if want to save data locally
    #   - ./data:/usr/src/app/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: byte_me_mongo
    ports:
      - "27017:27017" # Maps the default Mongo port to your host machine
    volumes:
      - mongo_data:/data/db # Maps the volume to Mongo's default data path
    restart: unless-stopped
    
  web-server:
    build:
      context: ./src/webServer # Builds using the Node Dockerfile we will create
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # We use the service name 'cpp-server' instead of an IP address!
      - CPP_SERVER_IP=cpp-server
      - CPP_SERVER_PORT=8080
      - PORT=8081
      - JWT_SECRET="d5ff86ee9cc528e3f72f50fb8746ba729d0ce4055249472657776a9e9c976de8"
    depends_on:
      - cpp-server # Ensures C++ boots up before Node.js
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
      - REACT_APP_API_URL=http://web-server:8081
    depends_on:
      - web-server
    restart: unless-stopped

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true # Keeps the interactive terminal open for CLI
    tty: true
    depends_on:
      - cpp-server
      - web-server

  seeder:
      image: node:20-alpine
      command: sh -c "echo 'Waiting 10s for web-server to boot...' && sleep 10 && echo 'Installing Bruno CLI...' && npm install -g @usebruno/cli && echo 'Running API Seeder (Populating Restaurants)...' && cd /app/bruno && bru run && echo 'Finished Seeding.'"
      volumes:
        - ./bruno:/app/bruno
      depends_on:
        - web-server



# 3. Declare the named volume at the very bottom of the file
volumes:
  mongo_data:
    # This ensures persistent storage so data isn't lost when containers stop